# This is a basic workflow to help you get started with Actions

name: passing job values

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
jobs:
  pass_in_one_job:
    runs-on: ubuntu-latest
    steps:
      - name: Set color
        id: color-selector
        run: echo "message='czerwony'" >> $GITHUB_OUTPUT
        
      - name: Get color
        run: echo "The selected color is ${{ steps.color-selector.outputs.selected-color }} "
        
  producer:
    runs-on: ubuntu-latest
    steps:
      - name: Make a sentence
        id: sentence_maker
        run: |
            echo "message='wiadomosc'" >> $GITHUB_OUTPUT
    outputs:
      output1: ${{ steps.sentence_maker.outputs.message }}
  consumer:
    runs-on: ubuntu-latest
    needs: [producer]
    steps:
      - name: Print the message
        run: |
          echo ${{ needs.producer.outputs.output1 }} 

  job_1:
    name: Add 3 and 7
    runs-on: ubuntu-latest
    steps:
      - shell: bash
        run: |
          expr 3 + 7 > test.txt
      - uses: actions/upload-artifact@v4
        with:
          name: my-artifact
          path: test.txt

  job_2:
    name: Multiply by 9
    needs: job_1
    runs-on: windows-latest
    steps:
      - uses: actions/download-artifact@v5
        with:
          name: my-artifact
      - shell: bash
        run: |
          value=`cat test.txt`
          echo $(expr $value \* 9) 
